### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by vertesy** [vertesy/pseudoBulk#1]
## Milestones to finalize the pipeline

- [x] Barcode export from Seurat
- [ ] Barcode de-duplications
- [ ] Find the cause of repeated qNames in the 10X aligned bam file

### Barcode de-duplications
- [ ] Explore: is it done by 10x ??
- [ ] Find solution via 10X or alternatively via a python script

## Possible future improvements
- [ ] Use the exact same index & reference to what 10X cell ranger uses.
- [ ] Make it directly executable directly on a 10X output folder (using the clustering that 10X does).

### Using the exact same index & reference
 → This is actually needed if you want to analyze 10X runs that have been mapped to the pre-mRNA reference

When you run the VBC RNAseq pipeline, provide the gene model (GTF) and the exact same human genome the use (you have to directly link both).

- `--gtf` to use exactly the same names
  - if you provide both `--gtf`  and `--fasta` it recreates the reference, see:
  - both `--gtf`  and `--fasta`  and`--saveReference` **but not `--genome` to save the custom reference**
  - Pass on to Maria → add it to the cextflow config
